export const imagens = {
    'cyrax': require('../../assets/characters/cyrax.png'),
    'ermac': require('../../assets/characters/ermac.png'),
    'humansmoke': require('../../assets/characters/humansmoke.png'),
    'jade': require('../../assets/characters/jade.png'),
    'jax': require('../../assets/characters/jax.png'),
    'kabal': require('../../assets/characters/kabal.png'),
    'kano': require('../../assets/characters/kano.png'),
    'kitana': require('../../assets/characters/kitana.png'),
    'kunglao': require('../../assets/characters/kunglao.png'),
    'liukang': require('../../assets/characters/liukang.png'),
    'mileena': require('../../assets/characters/mileena.png'),
    'nightwolf': require('../../assets/characters/nightwolf.png'),
    'reptile': require('../../assets/characters/reptile.png'),
    'scorpion': require('../../assets/characters/scorpion.png'),
    'sektor': require('../../assets/characters/sektor.png'),
    'shangtsung': require('../../assets/characters/shangtsung.png'),
    'sindel': require('../../assets/characters/sindel.png'),
    'smoke': require('../../assets/characters/smoke.png'),
    'sonya': require('../../assets/characters/sonya.png'),
    'stryker': require('../../assets/characters/stryker.png'),
    'subzero': require('../../assets/characters/subzero.png'),
    'unmasksubzero': require('../../assets/characters/unmasksubzero.png')
};