export const imagens = {
    'cyrax': require('../../assets/personagens/cyrax.png'),
    'ermac': require('../../assets/personagens/ermac.png'),
    'humansmoke': require('../../assets/personagens/humansmoke.png'),
    'jade': require('../../assets/personagens/jade.png'),
    'jax': require('../../assets/personagens/jax.png'),
    'kabal': require('../../assets/personagens/kabal.png'),
    'kano': require('../../assets/personagens/kano.png'),
    'kitana': require('../../assets/personagens/kitana.png'),
    'kunglao': require('../../assets/personagens/kunglao.png'),
    'liukang': require('../../assets/personagens/liukang.png'),
    'mileena': require('../../assets/personagens/mileena.png'),
    'nightwolf': require('../../assets/personagens/nightwolf.png'),
    'reptile': require('../../assets/personagens/reptile.png'),
    'scorpion': require('../../assets/personagens/scorpion.png'),
    'sektor': require('../../assets/personagens/sektor.png'),
    'shangtsung': require('../../assets/personagens/shangtsung.png'),
    'sindel': require('../../assets/personagens/sindel.png'),
    'smoke': require('../../assets/personagens/smoke.png'),
    'sonya': require('../../assets/personagens/sonya.png'),
    'stryker': require('../../assets/personagens/stryker.png'),
    'subzero': require('../../assets/personagens/subzero.png'),
    'unmasksubzero': require('../../assets/personagens/unmasksubzero.png')
};